<<<<<<< HEAD
# Generated by Django 3.2.3 on 2021-05-21 15:34
=======
# Generated by Django 3.2 on 2021-05-20 18:21
>>>>>>> d8c75042bd638b67c75c00e46a164dc508adf0ab

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_atestados_numero_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atestados',
            name='data_emissao',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
